Test new keyboard doc
FleksySDK/kebbie pull request #36
Opened 2024-05-27 14:12 UTC by QADavidCalvo

Add documentation to know how to test a new keyboard that is not supported yet by Kebbie

## 🔍️ Description

This documentation is mainly focused on how to set up an Android emulator and evaluate an Android keyboard.

## 🧐 Context

This doc should be a step by step guide to add or just test any keyboard with Kebbie

## ⚠️ Side-effects / Shortcomings

Maybe we can add some screenshots

## ✅ How this was tested ?

## 🌱 Checklist

- [ ] Perform self-review of my own code
- [ ] Comment the code, particularly in hard-to-understand areas
- [] Update the documentation accordingly to the new code
- [ ] Lint / format the code
- [ ] Update existing tests / Add new tests
- [ ] Tests are passing locally

2024-05-28 00:19 UTC, astariul commented
Thanks for the PR !

Having this additional page will be very helpful.

At the moment, there are some issues with the render; how did you test your changes ? If you do : 

```python
pip install -e ".[docs]"
mkdocs serve
```

You should be able to visualize the page by going to [http://127.0.0.1:8000/test_a_new_keyboard/](http://127.0.0.1:8000/test_a_new_keyboard/)

And then you can fix the rendering issues in the markdown file (like the bullet points or the admonitions)

2024-05-28 12:07 UTC, QADavidCalvo commented
Screenshots added and checked the render.

2024-05-29 01:14 UTC, astariul requested changes

2024-05-29 01:14 UTC, astariul commented on docs/test_a_new_keyboard.md
> +## Get full elements tree:
```suggestion
## Get full elements tree
```

2024-05-29 01:14 UTC, astariul commented on docs/test_a_new_keyboard.md
> +```
Any reason for choosing Firefox ? On my Android emulator, Firefox isn't installed by default. Since we use Chrome in the tests, why not using Chrome in the examples too ?

2024-05-29 01:14 UTC, astariul commented on docs/test_a_new_keyboard.md
> +Press the input field to open the keyboard in any application
```suggestion
Press the input field to open the keyboard in any application.
```

2024-05-29 01:14 UTC, astariul commented on docs/test_a_new_keyboard.md
> +Run the method `driver.getPageSource()` on your code
```suggestion
Run the method `driver.getPageSource()` on your code.
```

2024-05-29 01:14 UTC, astariul commented on docs/test_a_new_keyboard.md
> +Get the XML returned by that method and then filter it by the keyboard package (e.g. `com.newkeyboardCompany.newkeyboard`)
```suggestion
Get the XML returned by that method and then filter it by the keyboard package (e.g. `com.newkeyboardCompany.newkeyboard`).
```

2024-05-29 01:14 UTC, astariul commented on docs/test_a_new_keyboard.md
> +Find the keyboard frame coordinates, the layout size and the data of each key by checking the content-desc or the resource-id
```suggestion
Find the keyboard frame coordinates, the layout size and the data of each key by checking the `content-desc` or the `resource-id`.
```

2024-05-29 01:14 UTC, astariul commented on docs/test_a_new_keyboard.md
> +Get the root element of the keyboard and then the type for each key
```suggestion
Get the root element of the keyboard and then the type for each key.
```

2024-05-29 01:14 UTC, astariul commented on docs/test_a_new_keyboard.md
> +## Add a new keyboard to Kebbie:
```suggestion
## Add a new keyboard to Kebbie
```

2024-05-29 01:14 UTC, astariul commented on docs/test_a_new_keyboard.md
> +Add the name of the new keyboard in the available choices in the file `kebbie > kebbie > cmd.py`
```suggestion
Add the name of the new keyboard in the available choices in the file [`kebbie/cmd.py`](https://github.com/FleksySDK/kebbie/blob/main/kebbie/cmd.py)
```

2024-05-29 01:14 UTC, astariul commented on docs/test_a_new_keyboard.md
> +And in the file `kebbie > kebbie > emulator.py`
```suggestion
And in the file [`kebbie/emulator.py`](https://github.com/FleksySDK/kebbie/blob/main/kebbie/emulator.py)
```

2024-05-29 01:14 UTC, astariul commented on docs/test_a_new_keyboard.md
> +    If it’s an Android keyboard add it to the `instantiate_correctors` list in the `cmd.py` file
```suggestion
    If it’s an Android keyboard, add it to the `instantiate_correctors()` function in the [`kebbie/cmd.py`](https://github.com/FleksySDK/kebbie/blob/main/kebbie/cmd.py) file
```

2024-05-29 01:14 UTC, astariul commented on docs/test_a_new_keyboard.md
> +    If there is any content in the keyboard that we want to ignore from the mapping, add it in the `CONTENT_TO_IGNORE` list at the `emulator.py` file (e.g. `"Gallery"`)
```suggestion
    If there is any content in the keyboard that we want to ignore from the mapping, add it in the `CONTENT_TO_IGNORE` list in the [`kebbie/emulator.py`](https://github.com/FleksySDK/kebbie/blob/main/kebbie/emulator.py) file (e.g. `"Gallery"`)
```

2024-05-29 01:14 UTC, astariul commented on docs/test_a_new_keyboard.md
> +    If there is any content in the keyboard that we want to map with another name, add it in the `CONTENT_TO_RENAME` list at the `emulator.py` file (e.g. `"Find": "enter"`)
```suggestion
    If there is any content in the keyboard that we want to map with another name, add it in the `CONTENT_TO_RENAME` dictionary in the [`kebbie/emulator.py`](https://github.com/FleksySDK/kebbie/blob/main/kebbie/emulator.py) file (e.g. `"Find": "enter"`)
```

2024-05-29 01:14 UTC, astariul commented on docs/test_a_new_keyboard.md
> +Create a layout detector class with the keyboard name adding the methods to get the root, the keys and the suggestions (see the `GboardLayoutDetector` class for an example)
```suggestion
Create a layout detector class with the keyboard name adding the methods to get the root, the keys and the suggestions (see the `GboardLayoutDetector` class for an example).
```

2024-05-29 01:14 UTC, astariul commented on docs/test_a_new_keyboard.md
> +Finally, in the `__init__` method at the `emulator.py` file, add the name of the keyboard in the `Get the
```suggestion
Finally, in the `__init__` method in the [`kebbie/emulator.py`](https://github.com/FleksySDK/kebbie/blob/main/kebbie/emulator.py) file, add the name of the keyboard in the `Get the 
```

2024-05-29 01:14 UTC, astariul commented on docs/test_a_new_keyboard.md
> +## Test the new keyboard with Kebbie:
```suggestion
## Test the new keyboard with Kebbie
```

2024-05-29 01:14 UTC, astariul commented on docs/test_a_new_keyboard.md
> +First check the key mapping running the command `kebbie show_layout -K newkkeyboard`
```suggestion
First check the key mapping running the command `kebbie show_layout -K newkkeyboard`.
```

2024-06-03 14:36 UTC, QADavidCalvo commented on docs/test_a_new_keyboard.md
> +```
removed

2024-06-03 14:36 UTC, QADavidCalvo commented on docs/test_a_new_keyboard.md
> +Run the method `driver.getPageSource()` on your code
removed

2024-06-03 14:42 UTC, QADavidCalvo commented on docs/test_a_new_keyboard.md
> +Finally, in the `__init__` method at the `emulator.py` file, add the name of the keyboard in the `Get the
added

2024-06-03 14:45 UTC, QADavidCalvo commented
PR ready to re-check @astariul 
Please compile it locally to check the render too.

2024-06-03 22:46 UTC, astariul requested changes

2024-06-03 22:46 UTC, astariul commented on docs/test_a_new_keyboard.md
> +## Get full keyboard locators:
```suggestion
## Get full keyboard locators
```

2024-06-03 22:46 UTC, astariul commented on docs/test_a_new_keyboard.md
> +## Add a new keyboard to Kebbie:
```suggestion
## Add a new keyboard to Kebbie
```

2024-06-03 22:46 UTC, astariul commented on docs/test_a_new_keyboard.md
> +Once you have all the locators related with the keyboard, find the root element of the keyboard, the keyboard keys and suggestions elements
```suggestion
Once you have all the locators related with the keyboard, find the root element of the keyboard, the keyboard keys and suggestions elements.
```

2024-06-03 22:46 UTC, astariul commented on docs/test_a_new_keyboard.md
> +Create a layout detector class with the keyboard name adding the methods to get the root, the keys and the suggestions (see the `GboardLayoutDetector` class for an example)
```suggestion
Create a layout detector class with the keyboard name adding the methods to get the root, the keys and the suggestions (see the `GboardLayoutDetector` class for an example).
```

2024-06-04 07:43 UTC, astariul approved these changes
LGTM ! 👍

2024-06-04 07:48 UTC, merged