Add get page cource command
FleksySDK/kebbie pull request #38
Opened 2024-05-28 15:33 UTC by QADavidCalvo

Add get page cource inline command

## 🔍️ Description

This PR adds a command go get the page source of a keyboard

## 🧐 Context

The idea here is to get the keyboard elements easily to be able to know the id, class, text,...etc. of each element of the keyboard the user want to evaluate.

By default the whole page source is saved in the `keyboard_page_source.xml` file and can be printed out on the console with an optional parameter.

## ⚠️ Side-effects / Shortcomings

Right now it's getting the whole elements tree (it would be good to filter by the app package and store only the useful data) 

## ✅ How this was tested ?

`kebbie get_page_source -K <keyboard_name>`

With the optional parameter "-P" or "--print_page_source" to show the elements tree on console.

## 🌱 Checklist

- [ ] Perform self-review of my own code
- [ ] Comment the code, particularly in hard-to-understand areas
- [ ] Update the documentation accordingly to the new code
- [ ] Lint / format the code
- [ ] Update existing tests / Add new tests
- [ ] Tests are passing locally

2024-05-29 01:25 UTC, astariul requested changes

2024-05-29 01:25 UTC, astariul commented on docs/test_a_new_keyboard.md
> +* Then evaluate the keyboard with the command ```kebbie evaluate -K newkeyboard```
Why are you adding this document again in this PR ? I'm confused, I thought the documentation is added in your other PR (#36) ?

2024-05-29 01:25 UTC, astariul commented on kebbie/emulator.py
> +            for data in self.get_page_source.split("<android.widget.FrameLayout")
Is it working on your computer ??

When I run the code, I get : `AttributeError: 'SwiftkeyLayoutDetector' object has no attribute 'get_page_source'`

Which make sense, because `get_page_source` is a method of `Emulator` class, but here we are in a `LayoutDetector` class.

Am I missing something ?

2024-05-29 01:25 UTC, astariul commented on kebbie/cmd.py
> +            page_source = c.emulator.get_page_source(print_page_source=args.print_page_source)
Adding a method just for this is overkill IMO.

Just do : 

```suggestion
            page_source = c.emulator.driver.page_source
            
            if args.print_page_source:
                print(page_source)
```

2024-05-29 07:29 UTC, QADavidCalvo commented on docs/test_a_new_keyboard.md
> +* Then evaluate the keyboard with the command ```kebbie evaluate -K newkeyboard```
ooops

2024-05-30 00:38 UTC, astariul commented
The PR looks great (just have to fix the lint, but that's a detail).

Some feedback from my side : 

* IMO we shouldn't filter the XML document to keep only the elements of the keyboard. Because of 2 things : 
  * First, it requires the user to know the keyboard element name. And this is element is in the XML. But we can't access the XML without first specifying the element name. It's a chicken and egg problem !
  * In some cases, the keyboard doesn't have a element name (for example KeyboardKit), and we have to rely on other tricks to extract the key positions from the XML.
* The problem with this command to extract XML, is that we extract it only for the default layout (qwerty), but some issues with detection might lie in the numbers layout for example. So maybe, a better alternative is to not add an additional command, and instead have a `--debug` flag for `show_layout` command : we dump the XML files for each layout before switching to the next layout. So if there is an issue, we can just inspect the XML.

What do you think ?

2024-05-30 07:41 UTC, QADavidCalvo commented
I think in the other way round. This command gets the XML but not filters by any element, It filters only by the app package that can be know easily just running `adb shell pm list packages` and removes the other not needed elements (Android elementos, Chrome elements, etc)

The idea of the `get_page_source` command is just to find the elements to add later in the code to map the keys and the suggestions.

If we add a `--debug` parameter in the `show_layout` process the user must know in advance the elementos for the keys and suggestions to he will need to run the `driver.page_source()` command at the beginning.

2024-05-30 08:25 UTC, astariul commented
> It filters only by the app package that can be know easily just running adb shell pm list packages and removes the other not needed elements (Android elementos, Chrome elements, etc)

It may be easy to get the package id, but then :
* How do you deal with keyboards which do not include the package name in their elements ? (like KeyboardKit)
* How do you deal with keyboards on iOS ?

---

> the show_layout process the user must know in advance the elementos for the keys and suggestions to he will need to run the driver.page_source() command at the beginning.

That's not true, we can use a dummy LayoutDetector which will display/save the page source before the code try to access any element.

2024-05-30 08:26 UTC, astariul commented
For example, the XML for KeyboardKit pro : 

```xml
<?xml version="1.0" encoding="UTF-8"?>
<AppiumAUT>
  <XCUIElementTypeApplication type="XCUIElementTypeApplication" name="Messages" label="Messages" enabled="true" visible="true" accessible="false" x="0" y="0" width="393" height="852" index="0">
    <XCUIElementTypeWindow type="XCUIElementTypeWindow" enabled="true" visible="true" accessible="false" x="0" y="0" width="393" height="852" index="0">
      <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="true" accessible="false" x="0" y="0" width="393" height="852" index="0">
        <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="true" accessible="false" x="0" y="0" width="393" height="852" index="0">
          <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="true" accessible="false" x="0" y="0" width="393" height="852" index="0">
            <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="true" accessible="false" x="0" y="0" width="393" height="852" index="0">
              <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="true" accessible="false" x="0" y="0" width="393" height="852" index="0">
                <XCUIElementTypeNavigationBar type="XCUIElementTypeNavigationBar" name="CKChat" enabled="true" visible="true" accessible="false" x="0" y="53" width="393" height="86" index="0">
                  <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="true" accessible="false" x="0" y="53" width="393" height="86" index="0">
                    <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="true" accessible="false" x="0" y="53" width="393" height="86" index="0">
                      <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="true" accessible="false" x="0" y="53" width="393" height="86" index="0">
                        <XCUIElementTypeButton type="XCUIElementTypeButton" name="backButton" enabled="true" visible="true" accessible="true" x="0" y="63" width="44" height="45" index="0">
                          <XCUIElementTypeImage type="XCUIElementTypeImage" name="UINavigationBarBackIndicatorDefault.png" enabled="true" visible="true" accessible="false" x="16" y="75" width="13" height="22" index="0"/>
                        </XCUIElementTypeButton>
                        <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="true" accessible="false" x="60" y="57" width="273" height="82" index="1">
                          <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="true" accessible="false" x="171" y="57" width="51" height="61" index="0">
                            <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="true" accessible="false" x="171" y="57" width="51" height="61" index="0">
                              <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="true" accessible="false" x="171" y="57" width="51" height="61" index="0">
                                <XCUIElementTypeImage type="XCUIElementTypeImage" enabled="true" visible="true" accessible="false" x="171" y="62" width="51" height="51" index="0"/>
                              </XCUIElementTypeOther>
                            </XCUIElementTypeOther>
                          </XCUIElementTypeOther>
                          <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="true" accessible="false" x="143" y="117" width="107" height="14" index="1">
                            <XCUIElementTypeButton type="XCUIElementTypeButton" name="+1 (888) 555-1212" label="+1 (888) 555-1212" enabled="true" visible="true" accessible="true" x="143" y="117" width="107" height="14" index="0">
                              <XCUIElementTypeImage type="XCUIElementTypeImage" name="chevron.forward" label="Forward" enabled="true" visible="true" accessible="false" x="242" y="120" width="8" height="10" index="0"/>
                            </XCUIElementTypeButton>
                          </XCUIElementTypeOther>
                        </XCUIElementTypeOther>
                        <XCUIElementTypeButton type="XCUIElementTypeButton" name="FaceTime" label="FaceTime" enabled="true" visible="true" accessible="true" x="333" y="67" width="44" height="37" index="2">
                          <XCUIElementTypeStaticText type="XCUIElementTypeStaticText" enabled="true" visible="false" accessible="false" x="333" y="67" width="0" height="1" index="0"/>
                        </XCUIElementTypeButton>
                      </XCUIElementTypeOther>
                    </XCUIElementTypeOther>
                  </XCUIElementTypeOther>
                </XCUIElementTypeNavigationBar>
                <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="true" accessible="false" x="0" y="0" width="393" height="852" index="1">
                  <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="true" accessible="false" x="0" y="0" width="393" height="852" index="0">
                    <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="true" accessible="false" x="0" y="0" width="393" height="852" index="0">
                      <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="true" accessible="false" x="0" y="0" width="393" height="852" index="0">
                        <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="true" accessible="false" x="0" y="0" width="393" height="852" index="0">
                          <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="true" accessible="false" x="0" y="0" width="393" height="852" index="0">
                            <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="true" accessible="false" x="0" y="0" width="393" height="852" index="0">
                              <XCUIElementTypeOther type="XCUIElementTypeOther" name="MessageEntryView" enabled="true" visible="true" accessible="false" x="0" y="448" width="393" height="57" index="0">
                                <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="true" accessible="false" x="0" y="448" width="393" height="57" index="0">
                                  <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="true" accessible="false" x="0" y="448" width="393" height="57" index="0">
                                    <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="false" accessible="false" x="0" y="448" width="393" height="57" index="0"/>
                                    <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="true" accessible="false" x="0" y="448" width="393" height="57" index="1"/>
                                  </XCUIElementTypeOther>
                                  <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="true" accessible="false" x="0" y="448" width="393" height="57" index="1">
                                    <XCUIElementTypeButton type="XCUIElementTypeButton" name="Apps" label="Apps" enabled="true" visible="true" accessible="true" x="14" y="455" width="34" height="35" index="0"/>
                                  </XCUIElementTypeOther>
                                  <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="true" accessible="false" x="60" y="453" width="317" height="38" index="2">
                                    <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="false" accessible="false" x="60" y="453" width="317" height="38" index="0"/>
                                    <XCUIElementTypeScrollView type="XCUIElementTypeScrollView" enabled="true" visible="true" accessible="false" x="60" y="453" width="317" height="38"  [...]

2024-05-30 09:02 UTC, astariul commented
There should be only one way to do things.

Either we add another command, or we add the `--debug` flag, but let's not add both.

2024-05-30 10:27 UTC, QADavidCalvo commented
I'd prefer to use the get_page_source command as a initial step. If not the user will need to use the Appium Inspector or use another code (like me on Java) to connect Appium with the device and then use the `driver.page_source()` command

The --debug parameter can be replaced by adding `driver.page_source()` before the method to get the "numbers" layout.

I will set the code to don't filter the page source by any package if it's not found in the XML (to cover the iOS cases)

2024-05-30 10:34 UTC, astariul commented
> I'd prefer to use the get_page_source command as a initial step. If not the user will need to use the Appium Inspector or use another code (like me on Java) to connect Appium with the device and then use the driver.page_source() command  
The --debug parameter can be replaced by adding driver.page_source() before the method to get the "numbers" layout.

I think we misunderstood each other 😅 
As far as I think, adding the `--debug` parameter will do exactly that : display / save `driver.page_source()` right before getting the "numbers" layout. 

So there is no need to use Appium inspector or another code : you just run the command with the debug parameter, and it saves the XML file (and maybe crash, but at least we have the XML to debug).

---

> I will set the code to don't filter the page source by any package if it's not found in the XML (to cover the iOS cases)

If we choose this over the `--debug` flag, sounds good ! 👍

2024-05-31 00:25 UTC, astariul requested changes
Almost there 😅 
I added 2 comments, please check them out 👍

2024-05-31 00:25 UTC, astariul commented on kebbie/emulator.py
> +            self.typing_field.clear()
```suggestion
        self.typing_field.clear()
```

We should clear the typing field even though we don't get the layout

2024-05-31 00:25 UTC, astariul commented on kebbie/cmd.py
> +            file_path = os.path.join(folder_name, args.keyboard + "_" + args.page_source_file)
We don't want side-effects like the creation of folders.

I understand you want to provide this as a nice way to organize the files, but this is limiting for the user : they can't specify a file in another folder for example.

Instead, we should just stick to the path given in the argument `--page_source_file`, so the user can pass a file in another folder or do whatever he wants.

2024-06-02 23:45 UTC, astariul requested changes

2024-06-02 23:45 UTC, astariul commented on kebbie/cmd.py
> +            with open(args.keyboard + "_" + args.page_source_file, "w", encoding="utf-8") as file:
Users should be able to save the file in a different folder :
```suggestion
            with open(args.page_source_file, "w", encoding="utf-8") as file:
```

2024-06-03 07:27 UTC, astariul approved these changes
LGTM ! 👍

2024-06-03 07:31 UTC, merged